In [1]:
#Task 1 - 1

def division(n):
  try:
    return n/0
  except Exception as e:
    return "error occurred : %s"%(e)
division(5)

'error occurred : division by zero'

In [2]:
#Task 1 - 2

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
  for j in verbs:
    for k in objects:
      print(f"{i} {j} {k}")

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [5]:
#Task 2 - 1

import numpy as np

def vandermondeMatrix(inputvector, n, increasing):
    
    if not increasing:
        opmatrix = np.array([x**(n-1-i) for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    elif increasing:
        opmatrix = np.array([x**i for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    
    return opmatrix


inputvector = np.array([1,2,3,4,5])
coloumns = 3

outputmatrixinc = vandermondeMatrix(inputvector,coloumns,True)
outputmatrixdec = vandermondeMatrix(inputvector,coloumns,False)

print("vandermonde matrix in the increasing order of powers:\n",outputmatrixinc,"\n")
print("Vandermonde matrix in the decreasing order of powers:\n",outputmatrixdec,"\n")

vandermonde matrix in the increasing order of powers:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

Vandermonde matrix in the decreasing order of powers:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

